spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo
    username: root
    password: 123456asd
    #214环境
    #url: jdbc:mysql://127.0.0.1:3306/datauser
    #username: root
    #password: root
    #    url: jdbc:oracle:thin:@//192.168.1.5:1521/orcl
    #    username:
    #    password:
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: "config.decrypt=true;config.decrypt.key=dfdffdg"
    druid:
      #配置监控统计拦截的filters,去掉后监控界面sql将无法统计，‘wall'用于防火墙
      #filters: stat,wall,log4j
      #最大活跃数
      maxActive: 20
      #初始化数量
      initialSize: 5
      #最大连接等待超时时间
      maxWait: 60000
      #打开PSCache，并且指定每个连接PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #通过connectionProperties属性打开mergeSql功能；慢sql记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      minIdle: 5
      timeBetweenEvictionRunsMills: 60000
      minEvictabledleTimeMills: 3000000
      validationQuery: select 1 from dual
      testWhileldle: true
      testOnBorrow: false
      testOnRetrun: false
